### ISSUE TITLE
Question: Is extension buffering data

### ISSUE THREAD

**Issue by steelbrain** [RickySu/hhvm-ext-uv#5]
In Node, the read function is triggered quite frequently but I see that in Hack, the read callback is only triggered once. so my question is, is this extension buffering the data? If it's buffering, can we specify a buffering limit? so people can't flood our ram with infinite data.

**Comment by RickySu** [comment]
Read callback is  triggered when data received many times.If not, this is a bug. ;)
libuv provides an alloc_cb to tell you how many memory should be allocated.

here is the code.
https://github.com/RickySu/hhvm-ext-uv/blob/multiloop/src/uv_tcp.cpp#L85

After triggerd read callback, you should free memory.
https://github.com/RickySu/hhvm-ext-uv/blob/multiloop/src/uv_tcp.cpp#L103

As you see

_Extension does not buffer any data._

**Comment by steelbrain** [comment]
That's nice to know. Thanks!
